import { saveAutomationSettings, sendAutomationTestEmail } from '@/app/actions/automation';
import { getActiveWorkspaceContext } from '@/lib/workspace';
import { redirect } from 'next/navigation';
import { AI_COMMUNICATION_LANGUAGES, DEFAULT_AI_COMMUNICATION_LANGUAGE } from '@/lib/ai/languages';

const field = 'mt-1 w-full rounded-lg border border-[#D8E0EA] px-3 py-2 text-sm';
export default async function AutomationPage({ searchParams }: { searchParams: Promise<{ welcome?: string; test?: string }> }) {
  const context = await getActiveWorkspaceContext(); if ('error' in context) redirect('/login');
  const [{ data: settings }, { data: runs }] = await Promise.all([
    context.supabase.from('automation_settings').select('*').eq('workspace_id', context.workspaceId).maybeSingle(),
    context.supabase.from('automation_runs').select('*').eq('workspace_id', context.workspaceId).order('scheduled_for', { ascending: false }).limit(10),
  ]);
  const config = settings || { enabled:false, daily_search_enabled:true, enrichment_enabled:true, auto_send_enabled:false, daily_lead_limit:20, daily_email_limit:20, minimum_fit_score:65, target_industries:[], target_regions:[], run_time:'10:00', weekdays:[1,2,3,4,5], communication_language:DEFAULT_AI_COMMUNICATION_LANGUAGE, signature:'' };
  const params = await searchParams; const welcome = params.welcome;
  const latest = runs?.[0];
  return <div className="space-y-6">
    <div className="flex items-start justify-between gap-4"><div><h1 className="text-3xl font-bold text-[#002B6A]">Automação</h1><p className="mt-1 text-sm text-[#475569]">Configure uma vez. A Columb prospecta todos os dias.</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${config.enabled ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{config.enabled ? '● Automação ativa' : '○ Automação pausada'}</span></div>
    {welcome && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">Pronto. Agora defina os limites e ative a Columb quando quiser.</div>}
    {params.test === 'success' && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">E-mail de teste entregue. O envio automático já pode ser habilitado.</div>}
    {params.test === 'failed' && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">O teste não foi entregue por um provedor real. Verifique SMTP/Resend e EMAIL_SEND_MODE.</div>}
    <div className="grid gap-4 md:grid-cols-6">{[['Encontradas',latest?.leads_found],['Enriquecidas',latest?.leads_enriched],['Qualificadas',latest?.leads_qualified],['Preparados',latest?.emails_generated],['Enviados',latest?.emails_sent],['Ignoradas',latest?.leads_skipped]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-[#D8E0EA] bg-white p-4"><span className="text-2xl font-bold text-[#002B6A]">{Number(value)||0}</span><p className="text-xs text-[#475569]">{label}</p></div>)}</div>
    <form action={saveAutomationSettings} className="grid gap-5 lg:grid-cols-3">
      <Card title="Busca diária"><Toggle name="enabled" title="Automação ativa" checked={config.enabled}/><Toggle name="daily_search_enabled" title="Buscar novas leads" checked={config.daily_search_enabled}/><Label title="Leads por dia"><input className={field} name="daily_lead_limit" type="number" min="1" max="500" defaultValue={config.daily_lead_limit}/></Label><Label title="Nichos"><textarea className={field} name="target_industries" defaultValue={config.target_industries?.join(', ')}/></Label><Label title="Regiões"><textarea className={field} name="target_regions" defaultValue={config.target_regions?.join(', ')}/></Label></Card>
      <Card title="IA"><Toggle name="enrichment_enabled" title="Enriquecimento automático" checked={config.enrichment_enabled}/><Label title="Idioma da comunicação"><select className={field} name="communication_language" defaultValue={config.communication_language || DEFAULT_AI_COMMUNICATION_LANGUAGE}>{AI_COMMUNICATION_LANGUAGES.map((language)=><option key={language.code} value={language.code}>{language.label}</option>)}</select></Label><p className="-mt-2 text-xs leading-relaxed text-[#475569]">Usado nas análises, abordagens e e-mails gerados pela IA.</p><Label title="Score mínimo"><input className={field} name="minimum_fit_score" type="number" min="0" max="100" defaultValue={config.minimum_fit_score}/></Label><p className="rounded-lg bg-[#F7FAFF] p-3 text-xs text-[#475569]">0–39 baixa · 40–69 média · 70–100 alta. O contato disponível não determina o score.</p></Card>
      <Card title="Outreach"><Toggle name="auto_send_enabled" title="Permitir envio automático" checked={config.auto_send_enabled}/><Label title="E-mails máximos/dia"><input className={field} name="daily_email_limit" type="number" min="0" max="500" defaultValue={config.daily_email_limit}/></Label><Label title="Horário"><input className={field} name="run_time" type="time" defaultValue={String(config.run_time).slice(0,5)}/></Label><Toggle name="avoid_weekends" title="Evitar finais de semana" checked={!config.weekdays?.includes(0) && !config.weekdays?.includes(6)}/><Label title="Assinatura"><textarea className={field} name="signature" defaultValue={config.signature||''}/></Label></Card>
      <button className="rounded-xl bg-[#2D6BFF] px-5 py-3 font-semibold text-white lg:col-span-3">Salvar automação</button>
    </form>
    <form action={sendAutomationTestEmail} className="rounded-2xl border border-[#D8E0EA] bg-white p-5"><h2 className="font-bold text-[#002B6A]">Teste de envio</h2><p className="mt-1 text-sm text-[#475569]">O envio automático só funciona depois de uma entrega real bem-sucedida.</p><button className="mt-4 rounded-lg border border-[#2D6BFF] px-4 py-2 text-sm font-bold text-[#2D6BFF]">Enviar e-mail de teste</button>{config.email_configuration_tested_at&&<span className="ml-3 text-xs text-emerald-700">Configuração testada</span>}</form>
    <section className="rounded-2xl border border-[#D8E0EA] bg-white p-5"><h2 className="font-bold text-[#002B6A]">Histórico</h2><div className="mt-3 divide-y divide-[#D8E0EA]">{runs?.length ? runs.map((run:any)=><div key={run.id} className="flex flex-wrap items-center justify-between gap-2 py-3 text-sm"><span className="font-semibold text-[#002B6A]">{new Date(run.scheduled_for).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</span><span className="text-[#475569]">✓ {run.leads_found} encontradas · ✓ {run.leads_qualified} qualificadas · ✓ {run.emails_sent} enviadas</span><span className="text-xs capitalize text-[#475569]">{run.status}</span></div>) : <p className="py-6 text-sm text-[#475569]">A primeira execução aparecerá aqui.</p>}</div></section>
  </div>;
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-4 rounded-2xl border border-[#D8E0EA] bg-white p-5"><h2 className="font-bold text-[#002B6A]">{title}</h2>{children}</section>}
function Label({title,children}:{title:string;children:React.ReactNode}){return <label className="block text-xs font-semibold text-[#475569]">{title}{children}</label>}
function Toggle({name,title,checked}:{name:string;title:string;checked:boolean}){return <label className="flex items-center justify-between gap-3 text-sm font-semibold text-[#061A40]"><span>{title}</span><input name={name} type="checkbox" defaultChecked={checked} className="h-5 w-5 accent-[#2D6BFF]"/></label>}
